MVC/Controllers/LancamentoController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using API.Data;
using API.Models;

namespace MVC.Controllers
{
    public class LancamentoController : Controller
    {
        #region CONSTRUTOR
        private readonly Contexto _context;

        public LancamentoController(Contexto context)
        {
            _context = context;
        }
        #endregion

        #region VISUALIZAR

        // GET: Lancamento
        public async Task<IActionResult> Index(string? mes, string? ano)
        {
            _Ano(ano);
            _Mes(mes);

            var contexto = _context.Lancamentos.Include(l => l.Contas).Include(l => l.Jogadores)
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)));
            return View(await contexto.ToListAsync());
        }

        // GET: Lancamento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lancamento = await _context.Lancamentos
                .Include(l => l.Contas)
                .Include(l => l.Jogadores)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lancamento == null)
            {
                return NotFound();
            }

            return View(lancamento);
        }

        #endregion

        #region RECEITA
        public async Task<IActionResult> _Receita(string? mes, string? ano)
        {
            #region Parametros
            _Ano(ano);
            _Mes(mes);
            #endregion

            #region Receita Geral
            //Resumo Receita Geral
            var contextoReceita = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "E")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Sum(l => l.Valor);
            ViewBag.GeralReceita = contextoReceita;

            #endregion

            #region Receita Aberto
            //Resumo Receita Aberto
            var contextoReceitaAberto = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "E")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Where(l => l.DtBaixa == null)
                .Sum(l => l.Valor);
            ViewBag.GeralReceitaAberto = contextoReceitaAberto;

            #endregion

            #region Grupo Receita

            //Tipo Saldo
            //Falta passar Lista para view
            var contextoSaldoGrupoReceita = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "E")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)));
                //.Where(l => l.DtBaixa == null);
            /*.GroupBy(l => l.Contas.NomeConta).Select(l => new { l.Key, Soma = l.Sum(c => c.Valor) }); */ //Passar GroupBy para view para aparecer os grupos

            #endregion

            return View(contextoSaldoGrupoReceita);
        }

        #endregion

        #region DESPESA
        public async Task<IActionResult> _Despesa(string? mes, string? ano)
        {
            #region Parametros
            _Ano(ano);
            _Mes(mes);
            #endregion

            #region Despesa Geral
            //Resumo Receita Geral
            var contextoDespesa = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "S")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Sum(l => l.Valor);
            ViewBag.GeralDespesa = contextoDespesa;

            #endregion

            #region Despesa Aberto
            //Resumo Receita Aberto
            var contextoDespesaAberto = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "S")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Where(l => l.DtBaixa == null)
                .Sum(l => l.Valor);
            ViewBag.GeralDespesaAberto = contextoDespesaAberto;

            #endregion

            #region Grupo Despesa

            //Tipo Saldo
            //Falta passar Lista para view
            var contextoSaldoGrupoDespesa = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "S")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)));
            //.Where(l => l.DtBaixa == null);
            /*.GroupBy(l => l.Contas.NomeConta).Select(l => new { l.Key, Soma = l.Sum(c => c.Valor) }); */ //Passar GroupBy para view para aparecer os grupos

            #endregion

            return View(contextoSaldoGrupoDespesa);
        }

        #endregion

        #region EXTRATO

        public async Task<IActionResult> Extrato(string? ano)
        {
            #region Parametros
            _Ano(ano);
            #endregion

            var contextoExtrato = _context.Lancamentos.Include(l => l.Contas).Include(l => l.Jogadores)
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)));
            return View(contextoExtrato);
        }

        #endregion

        #region RESUMO

        // GET: Lancamento
        public async Task<IActionResult> Resumo(string? mes, string? ano)
        {
            #region Parametros
            _Ano(ano);
            _Mes(mes);
            #endregion

            #region ResumoGeral
            //Resumo Receita Geral
            var contextoReceita = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "E")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Sum(l => l.Valor);
            ViewBag.GeralReceita = contextoReceita;

            //Resumo Despesa Geral
            var contextoDespesa = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "S")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Sum(l => l.Valor);
            ViewBag.GeralDespesa = contextoDespesa;

            //Resumo Saldo Geral
            var contextoSaldo = contextoReceita + contextoDespesa;

            ViewBag.GeralSaldo = contextoSaldo;
            #endregion

            #region ResumoAberto
            //Resumo Receita Aberto
            var contextoReceitaAberto = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "E")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Where(l => l.DtBaixa == null)
                .Sum(l => l.Valor);
            ViewBag.GeralReceitaAberto = contextoReceitaAberto;

            //Resumo Despesa Aberto
            var contextoDespesaAberto = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Contas.Tipo == "S")
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)))
                .Where(l => l.DtBaixa == null)
                .Sum(l => l.Valor);
            ViewBag.GeralDespesaAberto = contextoDespesaAberto;

            //Resumo Saldo Aberto
            var contextoSaldoAberto = contextoReceitaAberto + contextoDespesaAberto;

            ViewBag.GeralSaldoAberto = contextoSaldoAberto;
            #endregion


            //Tipo Saldo
            var contextoTipoSaldo = _context.Lancamentos.Include(l => l.Jogadores).Include(l => l.Contas)
                .Where(l => l.Inativo == null)
                //.Where(l => l.DtBaixa == null)
                .Where(l => l.DtPrevisao.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.DtPrevisao.Month == Convert.ToInt32(_Mes(mes)));
                /*.GroupBy(l => l.Contas.NomeConta).Select(l => new { l.Key, Soma = l.Sum(c => c.Valor) }); */ //Passar GroupBy para view para aparecer os grupos



            return View(contextoTipoSaldo);
        }

        #endregion

        #region CRIAR

        // GET: Lancamento/Create
        public IActionResult Create()
        {
            ViewData["ContaId"] = new SelectList(_context.Contas.Where(l => l.Inativo == null), "Id", "NomeConta");

MVC/Views/Lancamento/Create.cshtml
@model API.Models.Lancamento

@{
    ViewData["Title"] = "Incluir";
}

<h1>Lançamento</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <form asp-action="Create" autocomplete="off">
        <div class="card border-secondary">
            <div class="card-header text-white text-center bg-warning" style="font-weight: bolder">Incluir</div>
            <div class="card-body text-secondary row d-flex justify-content-around">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-md-5">
                    <div class="form-group">
                        <div>
                            <label asp-for="DtPrevisao" class="control-label"></label>
                            <label style="color:brown"> *</label>
                        </div>
                        <input asp-for="DtPrevisao" class="form-control" />
                        <span asp-validation-for="DtPrevisao" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <div>
                            <label asp-for="Valor" class="control-label"></label>
                            <label style="color:brown"> *</label>
                        </div>
                        <input asp-for="Valor" class="form-control" />
                        <span asp-validation-for="Valor" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="ObsLancamento" class="control-label"></label>
                        <input asp-for="ObsLancamento" class="form-control" />
                        <span asp-validation-for="ObsLancamento" class="text-danger"></span>
                    </div>
                    <br />
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <div>
                            <label asp-for="ContaId" class="control-label"></label>
                            <label style="color:brown"> *</label>
                        </div>
                        <select asp-for="ContaId" class ="form-control" asp-items="ViewBag.ContaId"><option></option></select>
                        <span asp-validation-for="ContaId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        @*<div>*@
                            <label asp-for="JogadorId" class="control-label"></label>
                            @*<label style="color:brown"> *</label>
                        </div>*@
                        <select asp-for="JogadorId" class ="form-control" asp-items="ViewBag.JogadorId"><option></option></select>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="DtBaixa" class="control-label"></label>
                        <input asp-for="DtBaixa" class="form-control" />
                        <span asp-validation-for="DtBaixa" class="text-danger"></span>
                    </div>
                    <br />
                </div>
                @*<div class="form-group">
                    <label asp-for="Inativo" class="control-label"></label>
                    <input asp-for="Inativo" class="form-control" />
                    <span asp-validation-for="Inativo" class="text-danger"></span>
                </div>*@
                <br />
                <div class="form-group">
                    @*<input type="submit" value="Create" class="btn btn-primary" />*@
                    <button type="submit" class="btn btn-secondary">
                        <i class="fa fa-floppy-o"> Salvar</i>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

<br />
<hr />
<br />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-arrow-left"></i> Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Lancamento/Delete.cshtml
@model API.Models.Lancamento

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lancamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contas.NomeConta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jogadores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jogadores.Mensalista)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ObsLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ObsLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtPrevisao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtPrevisao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtBaixa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtBaixa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC/Views/Lancamento/Details.cshtml
@model API.Models.Lancamento

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Lancamento</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <form>
        <div class="card border-secondary">
            <div class="card-header text-white text-center bg-warning" style="font-weight: bolder">Detalhes</div>
            <div class="card-body text-secondary row d-flex justify-content-around">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label asp-for="DtPrevisao" class="control-label"></label>
                            <input asp-for="DtPrevisao" class="form-control" readonly/>
                        </div>
                        <br />
                        <div class="form-group">
                            <label asp-for="Valor" class="control-label"></label>
                            <input asp-for="Valor" class="form-control" readonly/>
                        </div>
                        <br />
                        <div class="form-group">
                            <label asp-for="ObsLancamento" class="control-label"></label>
                            <input asp-for="ObsLancamento" class="form-control" readonly/>
                        </div>
                        <br />
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label asp-for="ContaId" class="control-label"></label>
                            <input asp-for="ContaId" class="form-control" readonly/>
                        </div>
                        <br />
                        <div class="form-group">
                            <label asp-for="JogadorId" class="control-label"></label>
                            <input asp-for="JogadorId" class="form-control" readonly/>
                        </div>
                        <br />
                        <div class="form-group">
                            <label asp-for="DtBaixa" class="control-label"></label>
                            <input asp-for="DtBaixa" class="form-control" readonly/>
                        </div>
                        <br />
                    </div>
                    @*<div class="form-group">
                        <label asp-for="Inativo" class="control-label"></label>
                        <input asp-for="Inativo" class="form-control" />
                        <span asp-validation-for="Inativo" class="text-danger"></span>
                    </div>*@
                    <br />
                    <div>
                        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary"><i class="fa fa-pencil"></i> Editar</a>
                    </div>
            </div>
        </div>
    </form>
</div>

<br />
<hr />
<br />

@{
    ViewBag.mes = Model.DtPrevisao.Month;
    ViewBag.ano = Model.DtPrevisao.Year;
}
<div>
    <a asp-action="Index" asp-route-mes="@ViewBag.mes" asp-route-ano="@ViewBag.ano" class="btn btn-secondary"><i class="fa fa-list-ul"></i> Voltar</a>
</div>

MVC/Views/Lancamento/Edit.cshtml
@model API.Models.Lancamento

@{
    ViewData["Title"] = "Editar";
}

<h1>Lançamento</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <form asp-action="Edit" autocomplete="off">
        <div class="card border-secondary">
            <div class="card-header text-white text-center bg-warning" style="font-weight: bolder">Editar</div>
            <div class="card-body text-secondary row d-flex justify-content-around">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="col-md-5">
                    <div class="form-group">
                        <label asp-for="DtPrevisao" class="control-label"></label>
                        <input asp-for="DtPrevisao" class="form-control" />
                        <span asp-validation-for="DtPrevisao" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Valor" class="control-label"></label>
                        <input asp-for="Valor" class="form-control" />
                        <span asp-validation-for="Valor" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="ObsLancamento" class="control-label"></label>
                        <input asp-for="ObsLancamento" class="form-control" />
                        <span asp-validation-for="ObsLancamento" class="text-danger"></span>
                    </div>
                    <br />
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <label asp-for="ContaId" class="control-label"></label>
                        <select asp-for="ContaId" class="form-control" asp-items="ViewBag.ContaId"><option></option></select>
                        <span asp-validation-for="ContaId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="JogadorId" class="control-label"></label>
                        <select asp-for="JogadorId" class="form-control" asp-items="ViewBag.JogadorId"><option></option></select>
                        <span asp-validation-for="JogadorId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="DtBaixa" class="control-label"></label>
                        <input asp-for="DtBaixa" class="form-control" />
                        <span asp-validation-for="DtBaixa" class="text-danger"></span>
                    </div>
                    <br />
                </div>
                @*<div class="form-group">
                    <label asp-for="Inativo" class="control-label"></label>
                    <input asp-for="Inativo" class="form-control" />
                    <span asp-validation-for="Inativo" class="text-danger"></span>
                </div>*@
                <br />
                <div class="form-group">
                    @*<input type="submit" value="Save" class="btn btn-primary" />*@
                    <button type="submit" class="btn btn-secondary">
                        <i class="fa fa-floppy-o"> Salvar</i>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

<br />
<hr />
<br />
@{
    ViewBag.mes = Model.DtPrevisao.Month;
    ViewBag.ano = Model.DtPrevisao.Year;
}
<div>
    <a asp-action="Index" asp-route-mes="@ViewBag.mes" asp-route-ano="@ViewBag.ano" class="btn btn-secondary"><i class="fa fa-list-ul"></i> Voltar</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Lancamento/Index.cshtml
@model IEnumerable<API.Models.Lancamento>

@{
    ViewData["Title"] = "Lançamentos";
}

<br />
<h1 style="text-align:center">Financeiro</h1>
<h3 style="text-align:center">Lançamentos - <a>@ViewBag.Mes/@ViewBag.Ano</a></h3>
<br />

<hr />
<div class="boxWhite">
    <div class="d-flex justify-content-between">
        <a asp-action="Create" class="btn btn-secondary"><i class="fa fa-plus-circle"></i> Incluir</a>
        @using (Html.BeginForm("Index", "lancamento", FormMethod.Get))
        {
            <div class="containerForm">
                <div class="input-group">
                    <partial name="_Mes">
                
                    <partial name="_Ano">                
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Listar</button>
                    </div>
                </div>
            </div>
        }
        <a asp-action="Resumo" asp-route-mes="@ViewBag.mes" asp-route-ano="@ViewBag.ano" class="btn btn-secondary"><i class="fa fa-money"></i> Resumo</a>
        @*<a target="_blank" href="http://localhost:5172/api/lancamentos" class="btn" data-toggle="tooltip" data-html="true" title="API de Lançamentos">
            <i class="fa fa-plug"></i> <b> API</b>
        </a>*@
    </div>
    <hr />

    <table id="tabelaIndex" class="table table-responsive-sm table-striped table-hover">
        <thead style="color: white" class="bg-warning"> @*Am background-color: rgb(255,193,7) | Az rgb(37,88,126)*@
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DtPrevisao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contas)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Jogadores)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Valor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ObsLancamento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DtBaixa)
                </th>
                <th class="d-flex justify-content-center">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DtPrevisao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Contas.NomeConta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Jogadores.NomeJogador)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ObsLancamento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DtBaixa)
                    </td>
                    <td class="d-flex justify-content-center">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-default">
                            <i class="fa fa-pencil"></i> Editar
                        </a> | 
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-default">
                            <i class="fa fa-info"></i> Detalhes
                        </a> | 
                        <a onclick="Inativar(@item.Id)" class="btn btn-sm btn-default">
                            <i class="fa fa-trash"></i> Excluir
                        </a>
                        @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<hr />

@section Scripts {
    <script>
        //$(document).ready(function(){
        //    $('#tabelaIndex').DataTable( {
        //        "language": {
        //            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
        //        }
        //    });
        //}); // Partial Viewe _LayoutTabela

        $(function(){
            var successMessage = '@TempData["MsgSucesso"]'
            if(successMessage != '')
                alertify.success(successMessage);
        });  /*Função para receber valor de MsgSucesso da Controller e tratar para Alertify*/

        function Inativar(id) {
            alertify.confirm('Exclusão de Lançamento', 'Confirmar exclusão ?',function(){
                window.location.href = '@Url.Action("Inativar","Lancamento")/'+id;
            },null );
        } /*Função para Modal de confirmação de exclusão */
    </script>
    @Html.Partial("../Shared/_LayoutTabela")
}

MVC/Views/Lancamento/_Despesa.cshtml
@model IEnumerable<API.Models.Lancamento>


<tr class="table-secondary">
    <td class="tableDespesa" colspan="2">Despesa</td>
</tr>
@foreach (var item in Model.Where(l => l.Contas.Tipo == "S").GroupBy(l => l.Contas.NomeConta).Select(l => new { l.Key, Soma = l.Sum(c => c.Valor) }).OrderByDescending(l => l.Soma)) 
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Key)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Soma)
        </td>
    </tr>
}
<tr>
    <td class="tableDespesa">
        GERAL (Despesa)
    </td>
    <td class="tableDespesa">
        @ViewBag.GeralDespesa
    </td>
</tr>
<tr>
    <td class="tableDespesa">
        ABERTO (Despesa)
    </td>
    <td class="tableDespesa">
        @ViewBag.GeralDespesaAberto
    </td>
</tr>

MVC/Views/Lancamento/_Receita.cshtml
@model IEnumerable<API.Models.Lancamento>


<tr class="table-secondary">
    <td class="tableReceita" colspan="2">Receita</td>
</tr>
@foreach (var item in Model.Where(l => l.Contas.Tipo == "E").GroupBy(l => l.Contas.NomeConta).Select(l => new { l.Key, Soma = l.Sum(c => c.Valor) }).OrderByDescending(l => l.Soma)) 
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Key)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Soma)
        </td>
    </tr>
}
<tr>
    <td class="tableReceita">
        GERAL (Receita)
    </td>
    <td class="tableReceita">
        @ViewBag.GeralReceita
    </td>
</tr>
<tr>
    <td class="tableReceita">
        ABERTO (Receita)
    </td>
    <td class="tableReceita">
        @ViewBag.GeralReceitaAberto
    </td>
</tr>