MVC/Controllers/ContaController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using API.Data;
using API.Models;

namespace MVC.Controllers
{
    public class ContaController : Controller
    {
        #region CONSTRUTOR
        private readonly Contexto _context;

        public ContaController(Contexto context)
        {
            _context = context;
        }

        #endregion

        #region VISUALIZAR

        // GET: Conta
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contas.Where(c => c.Inativo == null).ToListAsync());
        }

        // GET: Conta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conta = await _context.Contas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (conta == null)
            {
                return NotFound();
            }

            return View(conta);
        }

        #endregion

        #region CRIAR

        // GET: Conta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Conta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomeConta,Tipo,ObsConta,Inativo")] Conta conta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(conta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(conta);
        }

#endregion

        #region EDITAR

        // GET: Conta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conta = await _context.Contas.FindAsync(id);
            if (conta == null)
            {
                return NotFound();
            }
            return View(conta);
        }

        // POST: Conta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeConta,Tipo,ObsConta,Inativo")] Conta conta)
        {
            if (id != conta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContaExists(conta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(conta);
        }

        #endregion

        #region DELETAR (Desativado)

        // GET: Conta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conta = await _context.Contas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (conta == null)
            {
                return NotFound();
            }

            return View(conta);
        }

        // POST: Conta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var conta = await _context.Contas.FindAsync(id);
            _context.Contas.Remove(conta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region DELETAR

        // GET: Conta/Edit/5
        public async Task<IActionResult> Inativar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conta = await _context.Contas.FindAsync(id);
            conta.Inativo = DateTime.Now;
            if (conta == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContaExists(conta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["MsgSucesso"] = "Deletado com Sucesso";  //Transportar valor de MsgSucesso para função de alertify
                return RedirectToAction(nameof(Index));
            }
            return View(conta);

        }

        #endregion

        private bool ContaExists(int id)
        {
            return _context.Contas.Any(e => e.Id == id);
        }
    }
}

MVC/Controllers/ScoutController.cs
#nullable disable
using API.Data;
using API.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//using System.Data.Entity;  //Erro - Substituir pelo using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace MVC.Controllers
{
    public class ScoutController : Controller
    {
        /*--------------------------------
        * Acrescentar campo Time em tabela Scout, que vai receber o Time que jogou em cada partida; 
        * Passar Mensalista S, E, ou N como parametro; 
        * Trabalhar no JSON de Scout;
        * -------------------------------------*/

        #region CONSTRUTOR
        private readonly Contexto _context;

        public ScoutController(Contexto context)
        {
            _context = context;
        }
        #endregion

        #region VISUALIZAR

        // GET: Scout
        public async Task<IActionResult> Index(string? ano, string? mensalista)
        {

            //if (dtInicial == null)
            //{
            //    dtInicial = DateTime.MinValue;
            //}

            //if (dtFinal == null)
            //{
            //    dtFinal = DateTime.Now;
            //}

            _Ano(ano);
            _Mensalista(mensalista);

            var contexto = _context.Scouts.Include(l => l.Jogadores).Include(l => l.Parametros)
                .Where(l => l.Inativo == null)
                .Where(l => l.DtPartida.Year == Convert.ToInt32(_Ano(ano)))
                .Where(l => l.Jogadores.Mensalista == _Mensalista(mensalista))
                .Where(l => l.Presente == 1);

            /*var contexto = from sct in _context.Scouts
                           join jog in _context.Jogadores on sct.JogadorId equals jog.Id
                           join par in _context.Parametros on sct.ParametroId equals par.Id
                           group sct by new
                           {
                               jog.NomeJogador
                           } into g
                           orderby g.Sum(s => s.Gol) descending
                           select new
                           {
                               Nome = g.Key.NomeJogador,
                               Gols = g.Sum(s => s.Gol)
                           };
            ViewData["scout"] = contexto;*/

            //ValidarMensalistaSemPresenca();
            return View(await contexto.ToListAsync());
        }

        #endregion

        #region CRIAR

        public IActionResult Tabela()
        {
            ViewData["JogadorIdA1"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA2"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA3"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA4"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA5"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA6"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA7"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA8"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA9"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdA10"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");

            ViewData["JogadorIdB1"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB2"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB3"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB4"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB5"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB6"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB7"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB8"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB9"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");
            ViewData["JogadorIdB10"] = new SelectList(_context.Jogadores.Where(j => j.Inativo == null), "Id", "NomeJogador");

            //ViewData["ParametroId"] = new SelectList(_context.Parametros, "Id", "DescParametro");
            return View();
        }

        // POST: Scout/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Tabela(DateTime DtPartida, String ObsScout,
            int jogA1, int golA1,
            int jogA2, int golA2,
            int jogA3, int golA3,
            int jogA4, int golA4,
            int jogA5, int golA5,
            int jogA6, int golA6,
            int jogA7, int golA7,
            int jogA8, int golA8,
            int jogA9, int golA9,
            int jogA10, int golA10,
            int jogB1, int golB1,
            int jogB2, int golB2,
            int jogB3, int golB3,
            int jogB4, int golB4,
            int jogB5, int golB5,
            int jogB6, int golB6,
            int jogB7, int golB7,
            int jogB8, int golB8,
            int jogB9, int golB9,
            int jogB10, int golB10,
            [Bind("Id,DtPartida,JogadorId,Presente,CodParametro,Gol,Assistencia,ObsScout,Inativo")] Scout scout)
        {
            var GolA = golA1 + golA2 + golA3 + golA4 + golA5 + golA6 + golA7 + golA8 + golA9 + golA10;
            var GolB = golB1 + golB2 + golB3 + golB4 + golB5 + golB6 + golB7 + golB8 + golB9 + golB10;


            //if (ModelState.IsValid)
            //{
            #region Jogadores Time A
            List<int> listaJogTimeA = new List<int>();
            listaJogTimeA.Add(scout.JogadorIdA1 = jogA1);
            //listaJogTimeA.Add(0);

            listaJogTimeA.Add((int)(scout.JogadorIdA2 = jogA2));

            listaJogTimeA.Add((int)(scout.JogadorIdA3 = jogA3));

            listaJogTimeA.Add((int)(scout.JogadorIdA4 = jogA4));

            listaJogTimeA.Add((int)(scout.JogadorIdA5 = jogA5));

            listaJogTimeA.Add((int)(scout.JogadorIdA6 = jogA6));

            listaJogTimeA.Add((int)(scout.JogadorIdA7 = jogA7));

            listaJogTimeA.Add((int)(scout.JogadorIdA8 = jogA8));

            listaJogTimeA.Add((int)(scout.JogadorIdA9 = jogA9));

            listaJogTimeA.Add((int)(scout.JogadorIdA10 = jogA10));
            #endregion

            #region Gols Time A
            List<int> listaGolTimeA = new List<int>();
            listaGolTimeA.Add((int)(scout.GolsA1 = golA1));

            listaGolTimeA.Add((int)(scout.GolsA2 = golA2));

            listaGolTimeA.Add((int)(scout.GolsA3 = golA3));

            listaGolTimeA.Add((int)(scout.GolsA4 = golA4));

            listaGolTimeA.Add((int)(scout.GolsA5 = golA5));

            listaGolTimeA.Add((int)(scout.GolsA6 = golA6));

            listaGolTimeA.Add((int)(scout.GolsA7 = golA7));

            listaGolTimeA.Add((int)(scout.GolsA8 = golA8));

            listaGolTimeA.Add((int)(scout.GolsA9 = golA9));

            listaGolTimeA.Add((int)(scout.GolsA10 = golA10));

            #endregion

            #region Jogadores Time B
            List<int> listaJogTimeB = new List<int>();
            listaJogTimeB.Add(scout.JogadorIdB1 = jogB1);
            //listaJogTimeB.Add(0);

            listaJogTimeB.Add((int)(scout.JogadorIdB2 = jogB2));

            listaJogTimeB.Add((int)(scout.JogadorIdB3 = jogB3));

            listaJogTimeB.Add((int)(scout.JogadorIdB4 = jogB4));

            listaJogTimeB.Add((int)(scout.JogadorIdB5 = jogB5));

            listaJogTimeB.Add((int)(scout.JogadorIdB6 = jogB6));

            listaJogTimeB.Add((int)(scout.JogadorIdB7 = jogB7));

            listaJogTimeB.Add((int)(scout.JogadorIdB8 = jogB8));

            listaJogTimeB.Add((int)(scout.JogadorIdB9 = jogB9));

            listaJogTimeB.Add((int)(scout.JogadorIdB10 = jogB10));
            #endregion

            #region Gols Time B
            List<int> listaGolTimeB = new List<int>();
            listaGolTimeB.Add((int)(scout.GolsB1 = golB1));

            listaGolTimeB.Add((int)(scout.GolsB2 = golB2));

            listaGolTimeB.Add((int)(scout.GolsB3 = golB3));

            listaGolTimeB.Add((int)(scout.GolsB4 = golB4));

            listaGolTimeB.Add((int)(scout.GolsB5 = golB5));

            listaGolTimeB.Add((int)(scout.GolsB6 = golB6));

            listaGolTimeB.Add((int)(scout.GolsB7 = golB7));

            listaGolTimeB.Add((int)(scout.GolsB8 = golB8));

            listaGolTimeB.Add((int)(scout.GolsB9 = golB9));

            listaGolTimeB.Add((int)(scout.GolsB10 = golB10));

            #endregion

            #region Regra de Negocio

            if (GolA > GolB)
            {
                for (int i = 0; i < listaJogTimeA.Count; i++)
                {
                    if (listaJogTimeA[i] != 0)
                    {
                        scout.Id = 0;
                        scout.DtPartida = DtPartida;

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GPS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" /> @*framework para ícone*@
    <link href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" rel="stylesheet" /> @*Script para indice e paginação de tabela -> 1 de 4*@
    <link href="~/css/alertify.min.css" rel="stylesheet"/> @*lib para modal e alerta 1de3 *@
    <link href="~/css/themes/default.min.css" rel="stylesheet" /> @*lib para modal e alerta 2de3*@
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GPS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Index">Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jogador" asp-action="Index">Jogadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lancamento" asp-action="Resumo">Financeiro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parametro" asp-action="Index">Parâmetros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scout" asp-action="Index">Scout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script> @*Script para indice e paginação de tabela -> 2 de 4*@
    <script src="~/js/alertify.min.js"></script> @*lib para modal e alerta 3de3*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC/Views/Shared/_LayoutGPS.cshtml
@{
    ViewData["empresa"] = "GPS";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.empresa | @ViewData["Title"]</title>
    <link rel="shortcut icon" href="~/img/logo.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" /> @*framework para ícone*@
    <link href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" rel="stylesheet" /> @*Script para indice e paginação de tabela -> 1 de 4*@
    <link href="~/css/alertify.min.css" rel="stylesheet"/> @*lib para modal e alerta 1de3 *@
    <link href="~/css/themes/default.min.css" rel="stylesheet" /> @*lib para modal e alerta 2de3*@
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" /> @*cdn para fonte da pagina*@
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow">
            <div class="container-fluid justify-content: space-around">
                <a asp-controller="Home" asp-action="Index"><img style="max-width: 120px" src="~/img/logo.png" /></a>
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home pr-3"></i> @ViewBag.empresa</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Scout" asp-action="Index">Scout</a>
                        </li><div class="vr"></div>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Lancamento" asp-action="Resumo">Financeiro</a>
                        </li><div class="vr"></div>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Cadastro">Cadastros</a>
                        </li><div class="vr"></div>
                        @*<li class="nav-item">
                            <a asp-area="" asp-controller="Jogador" asp-action="Index">Jogadores</a>
                        </li><div class="vr"></div>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Conta" asp-action="Index">Contas</a>
                        </li><div class="vr"></div>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Parametro" asp-action="Index">Parâmetros</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>        
    </header>

        <main role="main" class="pb-3">
    <div class="container">
            @RenderBody()
    </div>
        </main>

    <footer class="border-top footer text-muted">
        <div class="container-fluid rodape p-3 text-center">
            <a asp-controller="Home" asp-action="Index"><img style="max-width: 120px" src="~/img/logoBranco.png" /></a>
            <hr />
            <p>@ViewBag.empresa &copy; - @DateTime.Now.Year</p>
            <div class="sociais">
                <a target="_blank" href="https://github.com/douglasvdev"><i class="fa fa-github"></i></a>
                <a target="_blank" href="https://www.linkedin.com/in/douglasvaguiar"><i class="fa fa-linkedin-square"></i></a>
                <a target="_blank" href="https://www.instagram.com/douglasv.dev"><i class="fa fa-instagram"></i></a>
            </div>
        </div>
        @*<div class="container">
            &copy; 2022 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script> @*Script para indice e paginação de tabela -> 2 de 4*@
    <script src="~/js/alertify.min.js"></script> @*lib para modal e alerta 3de3*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC/Views/Shared/_LayoutTabela.cshtml
    <script>
        $(document).ready(function(){
            $('#tabelaIndex').DataTable( {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
                }
            });
        });

        /*$(function(){
            var successMessage = '@TempData["MsgSucesso"]'
            if(successMessage != '')
                alertify.success(successMessage);
        });  //Função para receber valor de MsgSucesso da Controller e tratar para Alertify

        function Inativar(id) {
            alertify.confirm('Exclusão de Conta', 'Confirmar exclusão ?',function(){
                window.location.href = '@Url.Action("Inativar","Conta")/'+id;
            },null );
        } //Função para Modal de confirmação de exclusão */
    </script>

MVC/Views/Shared/_Mes.cshtml
<select class="form-control" id="mes" name="mes">
    <option disabled selected>Mes</option>
    <option>1</option>
    <option>2</option>
    <option>3</option>
    <option>4</option>
    <option>5</option>
    <option>6</option>
    <option>7</option>
    <option>8</option>
    <option>9</option>
    <option>10</option>
    <option>11</option>
    <option>12</option>
</select>