MVC/Controllers/JogadorController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using API.Data;
using API.Models;

namespace MVC.Controllers
{
    public class JogadorController : Controller
    {
        #region CONSTRUTOR
        private readonly Contexto _context;

        public JogadorController(Contexto context)
        {
            _context = context;
        }
        #endregion

        #region VISUALIZAR

        // GET: Jogador
        public async Task<IActionResult> Index()
        {
            return View(await _context.Jogadores.Where(j => j.Inativo == null).ToListAsync());
        }

        // GET: Jogador/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogador = await _context.Jogadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jogador == null)
            {
                return NotFound();
            }

            return View(jogador);
        }

        #endregion

        #region CRIAR

        // GET: Jogador/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jogador/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomeJogador,Mensalista,ObsJogador,Inativo")] Jogador jogador)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jogador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jogador);
        }

        #endregion

        #region EDITAR

        // GET: Jogador/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogador = await _context.Jogadores.FindAsync(id);
            if (jogador == null)
            {
                return NotFound();
            }
            return View(jogador);
        }

        // POST: Jogador/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeJogador,Mensalista,ObsJogador,Inativo")] Jogador jogador)
        {
            if (id != jogador.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jogador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogadorExists(jogador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jogador);
        }

        #endregion

        #region DELETAR (Desativado)

        // GET: Jogador/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogador = await _context.Jogadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jogador == null)
            {
                return NotFound();
            }

            return View(jogador);
        }

        // POST: Jogador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jogador = await _context.Jogadores.FindAsync(id);
            _context.Jogadores.Remove(jogador);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region DELETAR

        // GET: Conta/Edit/5
        public async Task<IActionResult> Inativar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogador = await _context.Jogadores.FindAsync(id);
            jogador.Inativo = DateTime.Now;
            if (jogador == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jogador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogadorExists(jogador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["MsgSucesso"] = "Deletado com Sucesso";  //Transportar valor de MsgSucesso para função de alertify
                return RedirectToAction(nameof(Index));
            }
            return View(jogador);

        }

        #endregion

        private bool JogadorExists(int id)
        {
            return _context.Jogadores.Any(e => e.Id == id);
        }
    }
}

MVC/Views/Jogador/Create.cshtml
@model API.Models.Jogador

@{
    ViewData["Title"] = "Incluir";
}

<h1>Jogador</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card border-secondary row">
        <div class="card-header text-center" style="color: white; background-color: rgb(37,88,126); font-weight: bolder">Incluir</div>
        <div class="card-body text-secondary">
            <form asp-action="Create" autocomplete="off">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div>
                        <label asp-for="NomeJogador" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    <input asp-for="NomeJogador" class="form-control" />
                    <span asp-validation-for="NomeJogador" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div>
                        <label asp-for="Mensalista" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    @*<input asp-for="Mensalista" class="form-control upper" />*@
                    <select asp-for="Mensalista" class ="form-control" asp-items="ViewBag.ContaId">
                        <option>N</option>
                        <option>S</option>
                        <option>E</option>
                    </select>
                    <span asp-validation-for="Mensalista" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="ObsJogador" class="control-label"></label>
                    <input asp-for="ObsJogador" class="form-control" />
                    <span asp-validation-for="ObsJogador" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                    <label asp-for="Inativo" class="control-label"></label>
                    <input asp-for="Inativo" class="form-control" />
                    <span asp-validation-for="Inativo" class="text-danger"></span>
                </div>*@
                <br />
                <div class="form-group">
                    @*<input type="submit" value="Create" class="btn btn-primary" />*@
                    <button type="submit" class="btn btn-secondary">
                        <i class="fa fa-floppy-o"> Salvar</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<br />
<hr />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-arrow-left"></i> Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Jogador/Delete.cshtml
@model API.Models.Jogador

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jogador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeJogador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeJogador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensalista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensalista)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ObsJogador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ObsJogador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC/Views/Jogador/Details.cshtml
@model API.Models.Jogador

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Jogador</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card border-secondary row">
        <div class="card-header text-center" style="color: white; background-color: rgb(37,88,126); font-weight: bolder">Detalhes</div>
        <div class="card-body text-secondary">
            <form>
                <div class="form-group">
                    <label asp-for="NomeJogador" class="control-label"></label>
                    <input asp-for="NomeJogador" class="form-control" readonly/>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Mensalista" class="control-label"></label>
                    <input asp-for="Mensalista" class="form-control" readonly/>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="ObsJogador" class="control-label"></label>
                    <input asp-for="ObsJogador" class="form-control" readonly/>
                </div>
                <br />
                <div>
                    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary"><i class="fa fa-pencil"></i> Editar</a>
                </div>
            </form>
        </div>
    </div>
</div>

<br />
<hr />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-list-ul"></i> Lista</a>
</div>

MVC/Views/Jogador/Edit.cshtml
@model API.Models.Jogador

@{
    ViewData["Title"] = "Editar";
}

<h1>Jogador</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card border-secondary row">
        <div class="card-header text-center" style="color: white; background-color: rgb(37,88,126); font-weight: bolder">Editar</div>
        <div class="card-body text-secondary">
            <form asp-action="Edit" autocomplete="off">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <div>
                        <label asp-for="NomeJogador" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    <input asp-for="NomeJogador" class="form-control" />
                    <span asp-validation-for="NomeJogador" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div>
                        <label asp-for="Mensalista" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    @*<input asp-for="Mensalista" class="form-control upper" />*@
                    <select asp-for="Mensalista" class ="form-control" asp-items="ViewBag.ContaId">
                        <option>N</option>
                        <option>S</option>
                        <option>E</option>
                    </select>
                    <span asp-validation-for="Mensalista" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="ObsJogador" class="control-label"></label>
                    <input asp-for="ObsJogador" class="form-control" />
                    <span asp-validation-for="ObsJogador" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                    <label asp-for="Inativo" class="control-label"></label>
                    <input asp-for="Inativo" class="form-control" />
                    <span asp-validation-for="Inativo" class="text-danger"></span>
                </div>*@
                <br />
                <div class="form-group">
                    @*<input type="submit" value="Save" class="btn btn-primary" />*@
                    <button type="submit" class="btn btn-secondary">
                        <i class="fa fa-floppy-o"> Salvar</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<hr />
<br />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-list-ul"></i> Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Jogador/Index.cshtml
@model IEnumerable<API.Models.Jogador>

@{
    ViewData["Title"] = "Jogadores";
}

<br />
<h1 style="text-align:center">Jogadores</h1>
<br />

<hr />
<div class="boxWhite">
    <div class="d-flex justify-content-between">
        <a asp-action="Create" class="btn btn-secondary"><i class="fa fa-plus-circle"></i> Incluir</a>
        <a target="_blank" href="http://localhost:5172/api/jogadores" class="btn" data-toggle="tooltip" data-html="true" title="API de Jogadores">
            <i class="fa fa-plug"></i> <b>API</b>
        </a>
    </div>
    <hr />

    <table id="tabelaIndex" class="table table-responsive-sm table-striped table-hover">
        <thead style="color: white; background-color: rgb(37,88,126)">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Mensalista)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NomeJogador)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ObsJogador)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Inativo)
                </th>*@
                <th class="d-flex justify-content-center">Ação</th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Mensalista)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeJogador)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ObsJogador)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Inativo)
                </td>*@
                <td class="d-flex justify-content-center">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-default">
                        <i class="fa fa-pencil"></i> Editar
                    </a> | 
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-default">
                        <i class="fa fa-info"></i> Detalhes
                    </a> | 
                    <a onclick="Inativar(@item.Id)" class="btn btn-sm btn-default">
                            <i class="fa fa-trash"></i> Excluir
                    </a>
                    @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
    }
        </tbody>
    </table>
</div>
<hr />

@section Scripts {
    <script>
        //$(document).ready(function(){
        //    $('#tabelaIndex').DataTable( {
        //        "language": {
        //            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
        //        }
        //    });
        //}); //Partial View _LayoutTabela

        $(function(){
            var successMessage = '@TempData["MsgSucesso"]'
            if(successMessage != '')
                alertify.success(successMessage);
        });  /*Função para receber valor de MsgSucesso da Controller e tratar para Alertify*/

        function Inativar(id) {
            alertify.confirm('Exclusão de Jogador', 'Confirmar exclusão ?',function(){
                window.location.href = '@Url.Action("Inativar","Jogador")/'+id;
            },null );
        } /*Função para Modal de confirmação de exclusão */
    </script>
    @Html.Partial("../Shared/_LayoutTabela")
}