MVC/Controllers/ParametroController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using API.Data;
using API.Models;

namespace MVC.Controllers
{
    public class ParametroController : Controller
    {
        #region CONTRUTOR

        private readonly Contexto _context;

        public ParametroController(Contexto context)
        {
            _context = context;
        }

        #endregion

        #region VISUALIZAR

        // GET: Parametro
        public async Task<IActionResult> Index()
        {
            return View(await _context.Parametros.Where(p => p.Inativo == null).ToListAsync());
        }

        // GET: Parametro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parametro = await _context.Parametros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parametro == null)
            {
                return NotFound();
            }

            return View(parametro);
        }

#endregion

        #region CRIAR

        // GET: Parametro/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Parametro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DescParametro,CodParametro,Ponto,Inativo")] Parametro parametro)
        {
            if (ModelState.IsValid)
            {
                parametro.CodParametro = parametro.CodParametro.ToUpper();
                try
                {
                    _context.Add(parametro);
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    TempData["MsgRegDup"] = "Código já existe!";  //Transportar valor de MsgSucesso para função de alertify
                    return RedirectToAction(nameof(Create));
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parametro);
        }

#endregion

        #region EDITAR

        // GET: Parametro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parametro = await _context.Parametros.FindAsync(id);
            if (parametro == null)
            {
                return NotFound();
            }
            return View(parametro);
        }

        // POST: Parametro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DescParametro,CodParametro,Ponto,Inativo")] Parametro parametro)
        {
            if (id != parametro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                parametro.CodParametro = parametro.CodParametro.ToUpper();
                try
                {
                    _context.Update(parametro);
                    await _context.SaveChangesAsync();
                } 
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParametroExists(parametro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception ex)
                {
                    TempData["MsgRegDup"] = "Código já existe!";  //Transportar valor de MsgSucesso para função de alertify
                    return View(parametro);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parametro);
        }

#endregion

        #region DELETAR (Descontinuado)

        // GET: Parametro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parametro = await _context.Parametros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parametro == null)
            {
                return NotFound();
            }

            return View(parametro);
        }

        // POST: Parametro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var parametro = await _context.Parametros.FindAsync(id);
            _context.Parametros.Remove(parametro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region DELETAR

        // GET: Conta/Edit/5
        public async Task<IActionResult> Inativar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parametro = await _context.Parametros.FindAsync(id);
            parametro.Inativo = DateTime.Now;
            if (parametro == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parametro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParametroExists(parametro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["MsgSucesso"] = "Deletado com Sucesso";  //Transportar valor de MsgSucesso para função de alertify
                return RedirectToAction(nameof(Index));
            }
            return View(parametro);

        }

        #endregion

        #region METODOS

        private bool ParametroExists(int id)
        {
            return _context.Parametros.Any(e => e.Id == id);
        }

        #endregion
    }
}

MVC/Views/Parametro/Create.cshtml
@model API.Models.Parametro

@{
    ViewData["Title"] = "Incluir";
}

<h1>Parâmetro</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card border-secondary row">
        <div class="card-header text-center" style="color: white; background-color: rgb(37,88,126); font-weight: bolder">Incluir</div>
        <div class="card-body text-secondary">
            <form asp-action="Create" autocomplete="off">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div>
                        <label asp-for="DescParametro" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    <input asp-for="DescParametro" class="form-control" />
                    <span asp-validation-for="DescParametro" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div>
                        <label asp-for="CodParametro" class="control-label"></label>
                        <label style="color:brown"> *</label>
                        @if (TempData["MsgRegDup"] != null){<label style="color:brown"><strong>@TempData["MsgRegDup"]</strong></label>}
                    </div>
                    <input asp-for="CodParametro" class="form-control" />
                    <span asp-validation-for="CodParametro" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div>
                        <label asp-for="Ponto" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    <input asp-for="Ponto" class="form-control" />
                    <span asp-validation-for="Ponto" class="text-danger"></span>
                </div>
                <br />
                @*<div class="form-group">
                    <label asp-for="Inativo" class="control-label"></label>
                    <input asp-for="Inativo" class="form-control" />
                    <span asp-validation-for="Inativo" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    @*<input type="submit" value="Create" class="btn btn-primary" />*@
                    <button type="submit" class="btn btn-secondary" onclick="RegDup">
                        <i class="fa fa-floppy-o"> Salvar</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<br />
<hr />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-arrow-left"></i> Voltar</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

MVC/Views/Parametro/Delete.cshtml
@model API.Models.Parametro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Parametro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescParametro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescParametro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodParametro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodParametro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ponto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ponto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC/Views/Parametro/Details.cshtml
@model API.Models.Parametro

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card border-secondary row">
        <div class="card-header text-center" style="color: white; background-color: rgb(37,88,126); font-weight: bolder">Detalhes</div>
        <div class="card-body text-secondary">
            <form>
                <div class="form-group">
                    <label asp-for="DescParametro" class="control-label"></label>
                    <input asp-for="DescParametro" class="form-control" readonly/>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="CodParametro" class="control-label"></label>
                    <input asp-for="CodParametro" class="form-control" readonly/>
                </div>                    
                <br />                
                <div class="form-group">
                    <label asp-for="Ponto" class="control-label"></label>
                    <input asp-for="Ponto" class="form-control" readonly/>
                    <br />
                    <div>
                        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary"><i class="fa fa-pencil"></i> Editar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @*<div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

</div>

<br />
<hr />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-list-ul"></i> Lista</a>
</div>

MVC/Views/Parametro/Edit.cshtml
@model API.Models.Parametro

@{
    ViewData["Title"] = "Editar";
}

<h1>Parâmetros</h1>

<hr />
<br />

<div class="d-flex justify-content-center">
    <div class="card border-secondary row">
        <div class="card-header text-center" style="color: white; background-color: rgb(37,88,126); font-weight: bolder">Editar</div>
        <div class="card-body text-secondary">
            <form asp-action="Edit" autocomplete="off">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <div>
                        <label asp-for="DescParametro" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    <input asp-for="DescParametro" class="form-control" />
                    <span asp-validation-for="DescParametro" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div>
                        <label asp-for="CodParametro" class="control-label"></label>
                        <label style="color:brown"> *</label>
                        @if (TempData["MsgRegDup"] != null){<label style="color:brown"><strong>@TempData["MsgRegDup"]</strong></label>}
                    </div>
                    <input asp-for="CodParametro" class="form-control" />
                    <span asp-validation-for="CodParametro" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div>
                        <label asp-for="Ponto" class="control-label"></label>
                        <label style="color:brown"> *</label>
                    </div>
                    <input asp-for="Ponto" class="form-control" />
                    <span asp-validation-for="Ponto" class="text-danger"></span>
                </div>
                <br />
                @*<div class="form-group">
                    <label asp-for="Inativo" class="control-label"></label>
                    <input asp-for="Inativo" class="form-control" />
                    <span asp-validation-for="Inativo" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    @*<input type="submit" value="Save" class="btn btn-primary" />*@
                    <button type="submit" class="btn btn-secondary">
                        <i class="fa fa-floppy-o"> Salvar</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<hr />
<br />

<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="fa fa-list-ul"></i> Lista</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

MVC/Views/Parametro/Index.cshtml
@model IEnumerable<API.Models.Parametro>

@{
    ViewData["Title"] = "Index";
}

<br />
<h1 style="text-align:center">Parametros</h1>
<br />

<hr />
<div class="boxWhite">
    <div class="d-flex justify-content-between">
        <a asp-action="Create" class="btn btn-secondary"><i class="fa fa-plus-circle"></i> Incluir</a>
        <a target="_blank" href="http://localhost:5172/api/parametros" class="btn" data-toggle="tooltip" data-html="true" title="API de Contas">
            <i class="fa fa-plug"></i> <b>API</b>
        </a>
    </div>
    <hr />

    <table id="tabelaIndex" class="table table-responsive-sm table-striped table-hover">
        <thead style="color: white; background-color: rgb(37,88,126)">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DescParametro)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CodParametro)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ponto)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Inativo)
                </th>*@
                <th class="d-flex justify-content-center">Ação</th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DescParametro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CodParametro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ponto)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Inativo)
                </td>*@
                <td class="d-flex justify-content-center">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-default">
                        <i class="fa fa-pencil"></i> Editar
                    </a> | 
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-default">
                        <i class="fa fa-info"></i> Detalhes
                    </a> | 
                    <a onclick="Inativar(@item.Id)" class="btn btn-sm btn-default">
                        <i class="fa fa-trash"></i> Excluir
                    </a>
                    @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
    }
        </tbody>
    </table>
</div>
<hr />

@section Scripts {
    <script>
        //$(document).ready(function(){
        //    $('#tabelaIndex').DataTable( {
        //        "language": {
        //            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
        //        }
        //    });
        //}); //Partial View _LayoutTabela

        $(function(){
            var successMessage = '@TempData["MsgSucesso"]'
            if(successMessage != '')
                alertify.success(successMessage);
        });  /*Função para receber valor de MsgSucesso da Controller e tratar para Alertify*/

        function Inativar(id) {
            alertify.confirm('Exclusão de Parâmetro', 'Confirmar exclusão ?',function(){
                window.location.href = '@Url.Action("Inativar","Parametro")/'+id;
            },null );
        } /*Função para Modal de confirmação de exclusão */
    </script>
    @Html.Partial("../Shared/_LayoutTabela")
}